//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCLB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Ban
    {
        public Ban()
        {
            this.ThanhViens = new HashSet<ThanhVien>();
        }
    
        public int Id { get; set; }
        [DisplayName("Tên Ban")]
        public string TenBan { get; set; }
        [DisplayName("Mô tả")]
        public string MoTa { get; set; }
        public Nullable<int> ToChucId { get; set; }
    
        public virtual ToChuc ToChuc { get; set; }
        public virtual ICollection<ThanhVien> ThanhViens { get; set; }
    }
}
