//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCLB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoatDong
    {
        public int Id { get; set; }
        public Nullable<int> ToChucId { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string AnhChinh { get; set; }
    
        public virtual ToChuc ToChuc { get; set; }
    }
}
