//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCLB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ToChuc
    {
        public ToChuc()
        {
            this.Bans = new HashSet<Ban>();
            this.HoatDongs = new HashSet<HoatDong>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
            this.ThanhViens = new HashSet<ThanhVien>();
        }
    
        public int Id { get; set; }
        [DisplayName("Tên tổ chức")]
        public string Ten { get; set; }
        [DisplayName("Mô tả")]
        public string MoTa { get; set; }
        [DisplayName("Logo")]
        public string Logo { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Ngày thành lập")]
        public DateTime NgayThanhLap { get; set; }
        [DisplayName("Ngày giải thể")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayGiaiThe { get; set; }
    
        public virtual ICollection<Ban> Bans { get; set; }
        public virtual ICollection<HoatDong> HoatDongs { get; set; }
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
        public virtual ICollection<ThanhVien> ThanhViens { get; set; }
    }
}
